<div id="content-wrapper">
	<div class="row">
		<div class="col-lg-12">
			<?php //echo "<pre>", print_r($record), "</pre>";?>
			<div id="content-header" class="clearfix">
				<div class="pull-left">
					<ol class="breadcrumb">
						<li><a href="<?php echo base_url('Dashboard');?>">Dashboard</a></li>
						<li class="active"><span>Consumer Loan</span></li>
					</ol>
				</div>
			</div>
            <!--==================================================================-->
            <div class="main-box-body clearfix">
            	
				<?php $data=array(
                    "Cacao/Café",
                    "Sucre",
                    "Banane",
                    "Hévéa",
                    "Exploitation forestière",
                    "Industrie du bois",
                    "Or, diamant et fer",
                    "Cobalt",
                    "Exploration pétrolière",
                    "Entreprise Annexe aux services pétroliers",
                    "Electricité",
                    "Cacao/café",
                    "Coton",
                    "Ciment",
                    "Transformation de Bois",
                    "Transformation laitière",
                    "Transformation de Blé",
                    "Corps gras alimentaires",
                    "Autres agro-alimentaires",
                    "Boissons",
                    "Tabac",
                    "Aluminium",
                    "Parfum, cosmétiques et soins capillaires",
                    "Emballage",
                    "Transformation plastique",
                    "Chimie – Engrais",
                    "Raffinage Pétrole",
                    "Imprimerie",
                    "Savons, détergents et produits d’entretien",
                    "Santé & produits pharmaceutiques",
                    "Peintures, encres, colle et adhésif",
                    "Santé",
                    "Education",
                    "ENTREPRISE DE PLACEMENT",
                    "Immobilier",
                    "Banques et Autres services financiers",
                    "Assurances et Courtage",
                    "D’Entretien",
                    "Sécurité",
                    "Transport de marchandises",
                    "Transport Ferroviaire",
                    "Transport Aérien",
                    "Transport Maritime, Transit, Acconage, Manutention",
                    "Distribution Pétrole et Gaz",
                    "Services liés à l’exploration pétrolière",
                    "Filière de l’eau",
                    "Bâtiments et Travaux Publics",
                    "Tourisme et Hôtellerie",
                    "Télécommunications",
                    "Nouvelles Technologies",
                    "Contrôle qualité et AUDIT",
                    "Agence de communication",
                    "Médias",
                    "Autres services",
                    "Immobilier",
                    "Tabac, Vins et spiritueux",
                    "Matériaux de construction",
                    "Automobile, pneumatique et pièces détachées auto",
                    "Produits Pharmaceutiques",
                    "Produits alimentaires transformés",
                    "Aluminium",
                    "Commerce de détail",
                    "Administrations Centrale et décentralisée",
                    "Education",
                    "Portuaire",
                    "Aéroportuaire",
                    "Finances",
                    "Eau, Energie",
                    "Télécommunications",
                    "Communications",
                    "Bâtiments et TP",
                    "Autres",
                );
				$Employeurs=array(
								"Telcar", 
								"Olam Cam", 
								"SOSUCAM",
								"PHP",
								"SPM",
								"Delmonte",
								"HEVECAM",
								"SAFACAM",
								"CDC",
								"Gpe GWZ", 
								"Gpe ROUGIER", 
								"ALPICAM",
								"GRUMCAM", 
								"ALPI PF",
								"WIJMA", 
								"CAMIRON",  
								"GEOVIC",
								"SNH",
								"TOTAL", 
								"PECTEN", 
								"PERENCO", 
								"TURN BERRY", 
								"PHILIPS PETROLEUM", 
								"COTCO", 
								"Groupe BOCOM", 
								"PETROLEX",
								"NEPTURNE OIL",
								"ALPHA OIL CAMEROUN", 
								"BILLION CITY GAZ & OIL",  
								"AES SONEL", 
								"WARTSILA CENTRAL AFRICA",
								"K.POWER DEVELOPT CORP (KPDC)", 
								"DIBAMBA POWER DÉVELOPMENT CORP",
								"CHOCOCAM", 
								"SIC CACAO",
								"PRODUCAM",
								"SODECOTON", 
								"CIMENCAM", 
								"QUIFEROU",
								"CIMAF",
								"DANGOTE",
								"Gpe GWZ", 
								"Gpe ROUGIER", 
								"Gpe ALPICAM",  
								"SEPBC (STE D'EXPL. PARCS A BOIS CAM)",
								"CAMLAIT",
								"SGMC", 
								"PANZANI",
								"LA PASTA",				
								"SOCAPALM", 
								"SPFS (sté palmeraie. Ferme Suisse)",
								"SCR MAYA", 
								"PAMOL", 
								"SOSUCAM", 
								"SOCAPURSEL", 
								"SUMOCAM", 
								"AFRICA FOOD DISTRIBUTION",
								"OK FOOD",
								"FERRERO CAMEROUN",
								"SABC", 
								"GUINNESS", 
								"FERMENCAM", 
								"UNION CAMEROUNAISE DES BRASSERIES",
								"SOURCE DU PAYS",
								"BAT",
								"ALUCAM", 
								"SOCATRAL", 
								"ALUBASSA",
								"BIOPHARMA",		
								"MPL", 
								"SOCAVER", 
								"PLASTICAM",
								"ICRAFON",
								"ADER", 
								"YARA", 
								"PILCAM",
								"METAFRIQUE STEEL SA",
								"SONARA",
								"SAFCA", 
								"MOONGA SOGEDI", 
								"PRESSBOOK", 
								"MOORE PARAGON",
								"CAMEROUN CONTINU", 
								"MACACOS",
								"PRINT INDUSTRY SARL",
								"COLGATE PALMOLIVE CCIC", 
								"SOC",
								"SCR Maya", 
								"NOSA", 
								"COMPLEXE INDUSTRIEL DU LITTORAL(CIL)",
								"SANOFI SYNTHELABO",
								"SMALTO",
								"PIHSBURG PLATE GLASS SA (PPG)",
								"SHISONG GENERAL HOSPITAL CARDIAC CENTRE",
								"L’école LES RIBAMBELLES",
								"EMPLOI SERVICE",
								"HSD",
								"TEFFON RH",
								"EUROPE AFRIQUE INTERIM",
								"ESTA EMPLOI SERVICE",
								"PRO EMPLOI SERVICE",
								"SIC",
								"SGC", 
								"BICEC", 
								"ATTIJARI",
								"Groupe AFB", 
								"CFC ",
								"ALIOS", 
								"SRC", 
								"SNI", 
								"SCE", 
								"PRO-PME Financement",
								"UACAM Vie", 
								"AXA Assurance", 
								"AGF", 
								"Beneficial", 
								"ASCOMA", 
								"Activa", 
								"Chanas", 
								"Gras Savoye", 
								"GMC", 
								"ProAssur", 
								"NSIA",
								"CLEAN SERVICE SARL",
								"BU’MO SARL",
								"HYSACAM", 
								"SCHA",
								"G4S",
								"DAK",
								"TRANSVAL", 
								"ERG SECURITY",
								"AFRICA SECURITY",
								"SOLENA SARL", 
								"NECOTRANS", 
								"SOGIDO",
								"GEODIS WILSON",
								"COMPAGNIE DE COMMERCE ET DE TRANSPORT (CCT)",
								"BUSINESS CAR",
								"CAMRAIL", 
								"Air France", 
								"Swiss+", 
								"SN Brussels", 
								"Kenya Airways", 
								"Ethiopian Airways", 
								"RAM", 
								"CAMPORT PLC",			
								"SGS", 
								"GROUPE BOLLORÉ", 
								"MAERKS",
								"DAMCO", 
								"P&O NEDLLOYDS", 
								"GEODIS", 
								"SOCOMAR", 
								"TERMCOTANK", 
								"PANALPINA",
								"SOCOMAR", 
								"GETMA", 
								"FOURE LAGADEC CAMEROUN",
								"Total", 
								"Mobil", 
								"Tradex", 
								"CAMOA Air Liquide", 
								"MRS CORLAY",	
								"CONFEX OIL",
								"FME GAZ",
								"SCHLUMBERGER", 
								"B.K. HUGHES", 
								"HALLIBURGTON", 
								"TIDEWATER", 
								"SEDCO", 
								"MI OVERSEAS", 
								"FRIEDLANDER", 
								"TCL", 
								"COTCO", 
								"CAMWATER CDE",
								"RAZEL", 
								"SATOM", 
								"SIX INTER.",  
								"FOKOU", 
								"DRAGAGES", 
								"MAETUR", 
								"BATI SERVICES",  
								"METALUX",
								"GROUPEMENT PREMIER/",
								"YOSHIM ENTERPRISE", 
								"ASQUINI ENCORAD", 
								"BATI INTER COMMERCE", 
								"TRENCOS SARL", 
								"ATLANTIC CONSTRUCTION S.A", 
								"PICTET CAMEROUN",
								"BATI Plus",  
								"MONGO SARL",
								"MATICAM",
								"AIDA ENGINIERING SARL",
								"Hilton Hôtel", 
								"IBIS",
								"SAWA", 
								"MERIDIEN(PULLMAN)",
								"AKWA PALACE", 
								"SEME HOTEL",
								"HOTEL BANO PALACE",
								"MTN", 
								"ORANGE", 
								"CAMTEL", 
								"ERICSSON", 
								"RINGO",
								"YOOME", 
								"TELEINFRA",
								"INTELCIA CAMEROUN",
								"CFAO Technologies", 
								"MTN NS",  
								"IHS", 
								"ASTER GLOBAL SERVICES CAMEROUN ltd", 
								"OMNIUM CAMEROUN",
								"SGS", 
								"Bureau Veritas",
								"HYDRAC", 
								"NARIMI CONSULTING", 
								"KPMG", 
								"DELOITTE",  
								"PWC",  
								"MAZAR", 
								"ERSNT&YONG",
								"CAC INTERNATIONALE",
								"VOODOO", 
								"MW MARKETING",
								"OCEAN OGYLVY TENDANCES REGIE", 
								"CAMEROUNAISE D’IMPRESSIO ET DE COMMUNICATION", 
								"FASHION PLASTIC",
								"MULTIPRINT SERIGRAPHIE", 
								"RESYTAL SA", 
								"SOCIETE D’INTERMEDIATION COMMERCIALE ET DE TRANSPORT",
								"SPECTRUM", 
								"CANAL 2",
								"SOPECAM", 
								"DHL", 
								"Schneider Electric", 
								"CHRONOPOST",  
								"UPS",
								"SIC",
								"LA CLE DES CHATEAUX",
								"BERNABE FOKOU",  
								"SOREPCO",
								"BATIRAMA SARL",
								"CAMI", 
								"TRACTAFRIC", 
								"SOCADA", 
								"MITCAM", 
								"SMPC", 
								"DRIVING AND LOGISTICS (DAL)",
								"LABOREX", 
								"UC PHARM", 
								"CENAME", 
								"SODHEXO",
								"NEWREST CAMEROUN",
								"NESTLE", 
								"OLAM", 
								"UNILEVER", 
								"COLGATE PALMOLIVE",
								"SODIACAM",
								"SASEL",
								"SOPROICAM",
								"UNIMIX SA",
								"ALUBASSA", 
								"SOCATRAL",
								"ASTER GLOBAL",
								"LIKUSASA",
								"GROUPE MIM (SCORE CITY SPORT)", 
								"SODIACAM(super U)",
								"ARNO", 
								"MAHIMA", 
								"NIKKI", 
								"ONASHI (gpe mahima)",				
								"Ministères (fonctionnaires)",
								"Toutes les universités d’ETAT",				
								"PAD", 
								"Autorité Portuaire",
								"ERSI ADC", 
								"Autorité Aéronautique",				
								"CFC", 
								"CAA", 
								"FEICOM", 
								"CNPS", 
								"SNI", 
								"SRC", 
								"UNVDA",
								"SNH", 
								"CSPH", 
								"SONARA", 
								"ARSEL", 
								"ENEO", 
								"CAMWATER",
								"CAMTEL", 
								"ART",
								"CRTV",
								"Fonds Routier", 
								"SIC", 
								"MAETUR", 
								"MAGZI",
								"FNE", 
								"CENAME",
								"CAPP",
								"ARMP", 				
								"UNESCO",
								"UNHCR",
								"CICR",
								"HCR",
								"OAPI",
								"OMS",
								"OHADA",
								"PAM-CAMEROUN",
								"PNUD",
								"UA",
								"UE",
								"International All Supplies",
								"CABINET CHARLES TCHUENTE",
								"ARCHIDIOCESE DE BERTOUA ",
								"SACIM AUTOMOBILE",				

				);
				
				$Catégorieemployeurs=array(
					"Grande entreprise locale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Grande Enterprise Locale",
					"Grande entreprise locale",
					"Grande entreprise locale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Grande entreprise locale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Grande Enterprise Locale",
					"Grande entreprise locale",
					"Grande entreprise locale",
					"PME locale",
					"PME locale",
					"Multinationale",
					"Multinationale",
					"Grande entreprise locale",
					"Grande entreprise locale",
					"Multinationale",
					"Multinationale",
					"Grande entreprise locale",
					"Grande entreprise locale",
					"Multinationale",
					"Grande entreprise locale",
					"Grande entreprise régionale",
					"Grande entreprise régionale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"PME locale",
					"Grande entreprise locale",
					"Multinationale",
					"Grande entreprise locale",
					"Grande entreprise locale",	
					"Grande entreprise locale",
					"Grande entreprise locale",
					"Grande entreprise locale",
					"Grande entreprise locale",
					"Multinationale",
					"Multinationale",
					"PME locale",
					"PME locale",
					"PME locale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"PME locale",
					"Grande entreprise locale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Grande entreprise régionale",
					"Multinationale",
					"Grande Enterprise Locale",
					"Multinationale",
					"Grande entreprise locale",
					"Multinationale",
					"Grande entreprise locale",
					"PME locale",
					"Parapublique",
					"Grande entreprise locale",
					"Grande entreprise locale",
					"PME locale",
					"PME locale",
					"PME locale",
					"PME locale",
					"PME locale",
					"Multinationale",
					"Grande entreprise locale",
					"Grande entreprise locale",
					"PME locale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"PME locale",
					"PME locale",
					"PME locale",
					"PME locale",
					"PME locale",
					"PME locale",
					"PME locale",
					"PME locale",
					"PME locale",
					"Multinationale",
					"Multinationale",
					"Grande entreprise régionale",
					"Grande entreprise régionale",
					"Parapublique",
					"Multinationale",
					"Parapublique",
					"Parapublique",
					"Grande entreprise locale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Grande entreprise régionale",
					"Grande entreprise régionale",
					"Grande entreprise régionale",
					"Grande entreprise",
					"Multinationale",
					"Grande entreprise locale",
					"PME locale",
					"Grande entreprise régionale",
					"PME locale",
					"PME locale",
					"Grande entreprise locale",
					"PME locale",
					"Multinationale",
					"PME locale",
					"PME locale",
					"PME locale",
					"PME locale",
					"PME locale",
					"Multinationale",
					"PME locale",
					"Multinationale",
					"PME locale",	
					"PME locale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"PME locale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"PME local",
					"PME local",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Paraétatique",
					"Multinationale",
					"Multinationale",
					"Multinationale",			
					"Paraétatique",
					"PME locale",
					"PME locale",
					"PME locale",
					"PME locale",
					"PME locale",
					"PME locale",
					"PME locale",
					"PME locale",
					"Multinationale",
					"Multinationale",
					"PME locale",
					"Multinationale",
					"PME locale",
					"PME locale",
					"PME locale",
					"Grande enterprise régionale",
					"Multinationale",
					"Paraétatique",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Grande entreprise locale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"PME locale",
					"Grande entreprise régionale",
					"Multinationale",
					"PME locale",
					"PME locale",
					"Multinationale",
					"PME locale",
					"Paraétatique",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Grande entreprise locale",
					"PME local",
					"PME local",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"PME local",
					"Multinationale",
					"Multinationale",				
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"PME local",
					"PME local",
					"PME local",
					"PME local",
					"Multinationale",
					"Multinationale",
					"Multinationale",
					"PME locale",
					"Multinationale",
					"PME locale",
					"PME locale",
					"PME locale",
					"PME locale",
					"Etatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Grande entreprise régionale",
					"Grande entreprise régionale",
					"paratétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"Paraétatique",
					"ORGANISME INTERNATIONAL",
					"PME locale",
					"PME locale",
					"PME locale",
					"PME locale",
				);
				
$Limites =array(
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Max 36, anc. 1 an",
"Max 36, anc. 1 an",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Max 24 mois, 1 an, personnel administratif ",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"24 mois, anc. 1 an",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Max 36 mois anc 1",
"Tous",
"Tous",
"24 mois, anc. 1 an",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"24 mois",
"24 mois",
"24 mois",
"24 mois",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Découvert",
"cresco",
"Au Condition du PP",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Découvert",
"cresco",
"Découvert",
"cresco à employés postés à BACM",
"Tous",
"Tous",
"Découvert pour gardiens. CCT 24 mois pour personnel administratif",
"36 mois max",
"12 mois maxi",
"Tous",
"12 mois",
"Tous",
"Max 24mois anc 1an",
"Max 24mois anc 1an",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Découvert",
"cresco et CCT/24",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Découvert & Cresco",
"24 mois maxi",
"24 mois maxi",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"Tous",
"24 mois maxi",
"24 mois maxi",
"24 mois maxi",
"24 mois maxi",
"36 mois maxi",
"Découvert",
"cresco",
"Découvert",
"cresco",
"Découvert",
"cresco",
"Découvert",
"cresco",
"Découvert",
"cresco",
"Découvert",
"cresco",
"48 mois maxi",
"48 mois maxi",
"Tous",
"48 mois maxi",
"Découvert",
"cresco",
"Tous",
"Tous",
"Tous",
"Tous",
"Voir PP aux Particuliers et ses exceptions",
"Voir PP aux Particuliers et ses exceptions",
"Découvert",
"cresco",
"Découvert",
"cresco",
"CCT 24 Max",
"Découvert",
"cresco",
);



					/*sort() - sort arrays in ascending order
					rsort() - sort arrays in descending order
					asort() - sort associative arrays in ascending order, according to the value
					ksort() - sort associative arrays in ascending order, according to the key
					arsort() - sort associative arrays in descending order, according to the value
					krsort() - sort associative arrays in descending order, according to the key*/
					
					$unique = array_unique($Limites);					
					sort($unique);
					
				//echo "<pre>", print_r($unique,1), "</pre>";
				$result='';
				
				//echo count($unique);
				for($i=0; $i<count($unique); $i++)
				{
					
					//echo "<pre>", trim($unique[$i]), "</pre>";//secteurs
					//$result .=$this->db->insert('tbl_limites',array('limites'=>trim($unique[$i])));
					
				}
				if($result){
					//echo "success";
				}
				//tbl_employeurs
				//tbl_catégorie_employeurs
				
				
				?>
            </div>            
        </div>
      </div>
</div>


 
<script src="<?php echo  base_url(); ?>assets/js/demo-skin-changer.js"></script>  
<script src="<?php echo  base_url(); ?>assets/js/jquery.js"></script>
<script src="<?php echo  base_url(); ?>assets/js/bootstrap.js"></script>
<script src="<?php echo  base_url(); ?>assets/js/jquery.nanoscroller.min.js"></script>
<script src="<?php echo  base_url(); ?>assets/js/demo.js"></script>  


<script src="<?php echo  base_url(); ?>assets/js/raphael-min.js"></script>
<script src="<?php echo  base_url(); ?>assets/js/morris.js"></script>
<script src="<?php echo  base_url(); ?>assets/js/scripts.js"></script>
<script src="<?php echo  base_url(); ?>assets/js/pace.min.js"></script>

<script src="<?php echo  base_url(); ?>assets/js/bootstrap-wizard.js"></script>
<script src="<?php echo  base_url(); ?>assets/js/form-wizard"></script>
<script src="<?php echo  base_url(); ?>assets/js/select2.min.js"></script>

 </body>
 </html>




















